hbcmicroservicetemplate:
  image: sd1pgo01lx.saksdirect.com/my-first-service:<version>
  container_name: hbcmicroservicename
  hostname: <hostname>
  restart: always
  ports:
    - "9000:9000"
  volumes:
    - /saksservices/config:/opt/my-first-service-0.1/conf/custom
    - /saksservices/applogs/aem/hbc-microservice:/opt/my-first-service-0.1/logs
  labels:
    io.rancher.container.network: 'true'
  env_file:
    - ./ms.env
